name: Close Issues

on:
  repository_dispatch:
    inputs:
      commit_sha:
        required: true
      dry_run:
        required: false

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set date
        id: date
        run: |
          date=$(date +%Y.%m.%d)
          echo "::set-output name=today::$date"

      - uses: ./.github/actions/test
        with:
          commit_sha: ${{ inputs.commit_sha }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          dry_run: ${{ inputs.dry_run }}
