name: Close Issues
run-name: Auto Close Issues for ${{ github.event.client_payload.commit_sha }}

on:
  repository_dispatch:
    types: [auto-close-issues]

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set date
        id: date
        run: |
          date=$(date +%Y.%m.%d)
          echo "::set-output name=today::$date"

      - uses: ./.github/actions/test
        with:
          commit_sha: ${{ github.event.client_payload.commit_sha }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          dry_run: ${{ github.event.client_payload.dry_run }}
