name: Handbrake
on:
  workflow_dispatch:
    inputs:
      primary_staging:
        type: boolean
        required: false
      primary_production:
        type: boolean
        required: false

jobs:
  handbrake:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Read intellum yaml as json
        id: intellum-yaml
        uses: intellum/yq@v4.27.3
        with:
          cmd: |
            result=$(yq -o=json -I=0 ./.intellum.yml)
            echo $result

      - name: Configure handbrake
        id: handbrake-config
        uses: actions/github-script@v5
        with:
          script: |
            function addToHandbrake(cluster_stack, data) {
              const i = cluster_stack.lastIndexOf("_")
              const cluster = cluster_stack.slice(0, i)
              const stack = cluster_stack.slice(i + 1)

              if (!data.handbrake) data.handbrake = {}
              if (!data.handbrake[cluster]) data.handbrake[cluster] = []

              data.handbrake[cluster].push(stack)
            }

            const jsonStr = '${{ steps.intellum-yaml.outputs.result }}'
            let json = JSON.parse(jsonStr)
            delete json["handbrake"]

            const handbrake = {
              primary_staging: ${{ inputs.primary_staging }},
              primary_production: ${{ inputs.primary_production }}
            }

            for (const [key, value] of Object.entries(handbrake)) {
              if (value) addToHandbrake(key, json)
            }

            return json

      - name: Convert to yaml
        uses: intellum/yq@v4.27.3
        with:
          cmd: |
            json='${{ steps.handbrake-config.outputs.result }}'
            echo $json | yq -P > ./.intellum.yml

      - name: Output yaml file
        run: |
          cat .intellum.yml

      - name: heredoc
        run: |
          read -r -d '' result <<-"EOF"
          version `0.2.11`
          quotes 'test'
          EOF

          # echo "echo result"
          # echo $result
          # echo "printf result"
          # printf "%s\n" "$result"

      # - name: Push changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: ./.intellum.yml
      #     message: "handbrake [skip ci]"
