name: Handbrake
on:
  workflow_dispatch:
    inputs:
      primary_staging:
        type: boolean
        required: false
      primary_production:
        type: boolean
        required: false

jobs:
  handbrake:
    runs-on: ubuntu-latest

    steps:
      - name: Reset handbrake
        id: reset-handbrake
        uses: intellum/yq@v4.27.3
        with:
          cmd: |
            result=$(yq 'del(.handbrake)' .intellum.yml)

      - name: Output handbrake reset
        run: |
          cat > .intellum.yml <<-EOF
          ${{ steps.reset-handbrake.outputs.result }}
          EOF

      - name: Output yaml file
        run: |
          cat .intellum.yml
