name: Env Var Test
on:
  push:
    branches:
    - main
jobs:
  env-var-test:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Hello world action step
        id: hello
        uses: claycbr600/env-var-test@main
        env:
          MY_NAME: charlie
        with:
          who: 'Mona the Octocat'
