name: Matrix Test
on:
  push:
    branches:
    - main
jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name:
        run: echo hello

  matrix-test:
    needs: prepare
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        index: [1, 2]

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

  staging-image:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: zzz
        run: sleep 10

  post:
    needs: matrix-test
    runs-on: ubuntu-latest

    steps:
      - name: hello
        run: echo hello again

      - name: status checks
        uses: .github/actions/test/action.yml
