name: Matrix Test
on:
  push:
    branches:
    - main
jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name:
        run: echo hello

  matrix-test:
    needs: prepare
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        index: [1, 2]

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Test failure
        if: matrix.index == 1
        run: exit 1

  post:
    runs-on: ubuntu-latest

    steps:
      - name: hello
        run: echo hello again
