name: Test and Build Environment
on:
  push:
    branches:
    - main
    tags:
    - deploy-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
