name: Update Workflows

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@1.6
        with:
          file: ./params.yml
          key-path: '["branches"]'

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
