name: Update Workflows

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check packaging release branches
        id: packaging-branches
        uses: mikefarah/yq@v4.27.3
        with:
          cmd: yq -o json '.packaging.branches' < params.yml

      # - name: yq output
      #   run: |
      #     result=${{ steps.packaging-branches.outputs.result }}
      #     echo "result = $result"
      #     echo "::set-output name=yq::$result"

      - name: Set packaging branches value
        id: packaging
        run: |
          if [[ ${{ steps.packaging-branches.outputs.result }} == null ]]; then
            jsonStr='[]'
          else
            jsonStr=${{ toJSON(steps.packaging-branches.outputs.result) }}
          fi
          echo "jsonStr = $jsonStr"
          echo "::set-output name=branches::$jsonStr"

      - name: Get jenkins pkg builder job name
        id: deployment
        run: |
          if ${{ contains(fromJSON(steps.packaging.outputs.branches), github.head_ref) }}; then
            echo "found branch ${{ github.head_ref }}"
          else
            echo "no branch found"
          fi
