name: Update Workflows

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set date
        id: date
        run: |
          date=$(date +%Y.%m.%d)
          echo "::set-output name=today::$date"

      - uses: ./.github/actions/test
        with:
          commit_sha: 7698a9b9d075de2a4f6feaccd5974b4df53bac88
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          dry_run: ''
