name: Update Workflows

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check packaging release branches
        id: packaging-branches
        uses: KJ002/read-yaml@1.6
        with:
          file: ./params.yml
          key-path: '["packaging_branches"]'
        continue-on-error: true

      - name: Set packaging branches value
        id: packaging
        run: |
          jsonStr=${{ toJSON(steps.packaging-branches.outputs.data) }}
          if [[ -z $jsonStr || $jsonStr == 'null' ]]; then
            jsonStr='[]'
          fi
          echo "jsonStr = $jsonStr"
          echo "::set-output name=branches::$jsonStr"

      - name: Get jenkins pkg builder job name
        id: deployment
        run: |
          if ${{ contains(fromJSON(steps.packaging.outputs.data), github.head_ref) }}; then
            echo "found branch ${{ github.head_ref }}"
          else
            echo "no branch found"
          fi
