name: Update Workflows

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check packaging release branches
        id: packaging-branches
        uses: KJ002/read-yaml@1.6
        with:
          file: ./params.yml
          key-path: '["packaging", "release", "branches"]'

      - name: Set packaging branches value
        id: packaging
        run: |
          jsonStr=${{ steps.packaging-branches.outputs.data }}
          if [[ -z $jsonStr ]]; then
            jsonStr='[]'
          fi
          echo "::set-output name=branches::$jsonStr"

      - name: Get jenkins pkg builder job name
        id: deployment
        run: |
          head_ref=${{ github.head_ref }}
          branches=${{ steps.packaging.outputs.branches }}
          echo "head_ref = $head_ref"
          echo "branches = $branches"
