name: Update Workflows

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@1.6
        with:
          file: ./params.yml
          key-path: '["branches"]'

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"

      - name: yaml contains item
        run: |
          value=${{ contains(fromJson(steps.yaml-data.outputs.data), 'captain america') }}
          echo "captain america = $value"

      - name: read-yaml empty
        id: yaml-empty
        uses: KJ002/read-yaml@1.6
        with:
          file: ./params.yml
          key-path: '["blah"]'

      - name: yaml contains item
        run: |
          value=${{ contains(fromJson(steps.yaml-empty.outputs.data), 'captain america') }}
          echo "captain america = $value"

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-empty.outputs.data }}"
