name: Update Workflows

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: action-test
        uses: ./.github/actions/test
        with:
          app_name: charlie

      - name: Check packaging release branches
        id: packaging-branches
        uses: mikefarah/yq@v4.27.3
        with:
          cmd: |
            result=$(yq -o=json -I=0 '.packaging.branches' params.yml)
            if [[ $result == null ]]; then
              result='[]'
            fi
            echo $result

      - name: Get jenkins pkg builder job name
        id: deployment
        run: |
          if ${{ contains(fromJSON(steps.packaging-branches.outputs.result), github.head_ref) }}; then
            echo "found branch ${{ github.head_ref }}"
          else
            echo "no branch found"
          fi
